services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:80"
    volumes:
      - type: bind
        source: gebkis-frontend
        target: /usr/share/nginx/html/gebkis-frontend
      - type: bind
        source: logs
        target: /workspace/logs
      - type: bind
        source: nginx.conf
        target: /etc/nginx/nginx.conf
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - TENANT_ID=${TENANT_ID}
      - SITE_ID=${SITE_ID}
      - DRIVE_ID=${DRIVE_ID}
      - EXCEL_FILE_PATH=${EXCEL_FILE_PATH}
      - IMAGE_FOLDER_PATH=${IMAGE_FOLDER_PATH}
      - LOG_DIR=${LOG_DIR}
      - GEBKIS_DIR=${GEBKIS_DIR}
      - GEBKIS_IMG_DIR=${GEBKIS_IMG_DIR}
      - PYTHONUNBUFFERED=1
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
