services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:80"
    volumes:
      - ./gebkis-frontend:/usr/share/nginx/html/gebkis-frontend
      - ./logs:/workspace/logs
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - TENANT_ID=${TENANT_ID}
      - SITE_ID=${SITE_ID}
      - DRIVE_ID=${DRIVE_ID}
      - EXCEL_FILE_PATH=${EXCEL_FILE_PATH}
      - IMAGE_FOLDER_ID=${IMAGE_FOLDER_ID}
      - LOG_DIR=${LOG_DIR}
      - GEBKIS_DIR=${GEBKIS_DIR}
      - GEBKIS_IMG_DIR=${GEBKIS_IMG_DIR}
      - PYTHONUNBUFFERED=1
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
