version: '3'
services:
  web:
    build: .
    ports:
      - "6001:80"
    environment:
      - CLIENT_ID=
      - CLIENT_SECRET=
      - TENANT_ID=
      - SITE_ID=
      - DRIVE_ID=
      - ITEM_ID=
      - IMAGE_FOLDER_ID=
      - GEBKIS_DIR=/usr/share/nginx/html/data/Geburtstagsliste.xls
      - GEBKIS_IMG_DIR=/usr/share/nginx/html/images
      - PYTHONUNBUFFERED=1
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
