events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name localhost;
        
        root /usr/share/nginx/html;  # Dies sollte auf den richtigen Pfad verweisen
        index index.html;

        # Root location (Hauptseite)
        location / {
            try_files $uri $uri/ =404;
        }

        # Bereitstellung von .xlsx-Dateien mit dem richtigen MIME-Type
        location ~* \.xlsx$ {
            add_header Content-Type application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;
            try_files $uri =404;
        }

        # Bereitstellung von Bildern (wie jpg, png, gif etc.)
        location /images/ {
            alias /usr/share/nginx/html/app/images/;
            try_files $uri =404;
        }

        # Bereitstellung von Excel-Daten (Geburtstagsliste.xls)
        location /data/ {
            alias /usr/share/nginx/html/app/data/;
            try_files $uri =404;
        }
    }
}
